apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
{{ .Values.config.fluentbit.conf | indent 4 }}
  parsers.conf: |
{{ .Values.config.parsers.conf | indent 4 }}

